version: '2'
services:
  teamspeak:
    image: mbentley/teamspeak
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - $PWD/data:/data:rw
    ports:
      - '9987:9987/udp'
      - '30033:30033'
      - '10011:10011'
      - '41144:41144'
